version: '3.9'

networks:
  backend:

services:
  php-server:
    build:
      context: .
      dockerfile: ./php-server/Dockerfile
    container_name: '${APP_NAME}-php-server'
    working_dir: /var/www/
    environment:
     - 'DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASS}@db_server:3306/${MYSQL_DB}?serverVersion=10.5'
     - 'TZ = ${WORKSPACE_TIMEZONE}'
    ports:
      - 9000:9000
    volumes:
      - ./projects:/var/www/
      - ./php-server/php/php.ini:/usr/local/etc/php/conf.d/extra-php-config.ini
    depends_on:
      db_server:
        condition: service_healthy
    networks:
      - backend

  db_server:
    image: mysql:8.0.31
    container_name: '${APP_NAME}-db-server'
    restart: always
    ports:
      - '${DB_PORT}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASS}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASS}'
      MYSQL_DATABASE: '${MYSQL_DB}'
      TZ: '${WORKSPACE_TIMEZONE}'
    volumes:
      - db_data:/var/lib/mysql
      - ./db/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    healthcheck:
      test: curl --fail http://localhost || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    networks:
      - backend

  db_admin:
    image: phpmyadmin/phpmyadmin:5
    container_name: '${APP_NAME}-db-myadmin'
    ports:
      - '${APP_DB_ADMIN_PORT}:80'
    environment:
      PMA_HOST: db_server
      TZ: '${WORKSPACE_TIMEZONE}'
    restart: always
    depends_on:
      db_server:
        condition: service_healthy
    volumes:
      - db_admin_data:/var/www/
    networks:
      - backend

  web_server:
    image: nginx:latest
    container_name: '${APP_NAME}-web-server'
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - ./projects:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx/
    depends_on:
      db_server:
        condition: service_healthy
    environment:
      TZ: '${WORKSPACE_TIMEZONE}'
    restart: always
    networks:
      - backend

volumes:
  db_data:
  db_admin_data: